my_ctrig=input('Введите ваше имя ')
print("Здравствуйте,", my_ctrig)
print(type(my_ctrig))
print(len(my_ctrig))
print(my_ctrig .upper())
print(my_ctrig.lower())
print(my_ctrig.replace(' ',""))
print(my_ctrig[0])
print(my_ctrig[-1])
# Добавил еще немного данных, чтобы потренироваться и попробовать
#my_ctrig=input('Введите ваше имя ')
#date_of_birth=(input('В каком году вы родились? '))
#age=current_year-int(date_of_birth)
#print('В этом году вам исполнилось,',age)
#print("Здравствуйте,", my_ctrig)
#print(len(my_ctrig),(age))
#print(type(my_ctrig))
#print(my_ctrig .upper())
#print(my_ctrig.lower())
#print(my_ctrig.replace(' ',""))
#print(my_ctrig[0])
#print(my_ctrig[-1])